### ISSUE TITLE
无法获取百度指数

### ISSUE THREAD

**Issue by grandioserver** [longxiaofei/spider-BaiduIndex#57]
换了几个COOKIE，在不同电脑上，不同网络环境下，都无法获取到指数数据

**Comment by longxiaofei** [comment]
登录之后，浏览百度指数网页，然后再请求baidu.com，复制这个请求的cookie。

或

使用
```
from qdata.baidu_login import get_cookie_by_qr_login

if __name__ == "__main__":
    print(get_cookie_by_qr_login())
```

**Comment by grandioserver** [comment]
[代码截图](https://imgur.com/a/w0qhjdF)

按大佬说的方法获取了cookie，还行不咋行，前几周跑这个脚本都没啥问题，这周fail了好多

**Comment by longxiaofei** [comment]
1. 安装qdata 
```
pip uninstall pycrypto  # 避免与pycryptodome冲突
pip install --upgrade qdata
```

2. 运行`python3 examples/test_baidu_login.py`, 获取cookie

3. 将获取的cookie放到`./examples/test_baidu_index.py`里，运行`python3 examples/test_baidu_index.py`，观察是否输出正常

**Comment by grandioserver** [comment]
>     2\. python3 examples/test_baidu_index.py

[输出结果异常](https://imgur.com/a/aqZXpgj

重新建了一个虚拟环境，只装了一个qdata，结果还是error

**Comment by longxiaofei** [comment]
确认一下这个账号是否可以正常访问百度指数网站?

**Comment by cishengciyin** [comment]
出现同样的问题

**Comment by grandioserver** [comment]
> 确认一下这个账号是否可以正常访问百度指数网站?

可以正常登录访问百度指数网站。

**Comment by longxiaofei** [comment]
> > 确认一下这个账号是否可以正常访问百度指数网站?
> 
> 可以正常登录访问百度指数网站。

如果不介意的话，可以将这个账号的cookie发送到我邮箱吗?  libra.19951002@gmail.com

**Comment by cishengciyin** [comment]
登录账号可以正常访问的

data的数据格式好像改了


Cookie: BIDUPSID=A1687674F5C670CF4366653E6F345CA5; PSTM=1507613496; BD_UPN=12314753; __yjs_duid=1_6e5258f2dd8651d6b8a78296fccbeb7c1620185686013; BDUSS=w5MTNla0VmTkJCdlRxMnM3bEVEelpjc2ZRZkZ-TzBhTklPWWZnVXd5Y0tnaXhoRVFBQUFBJCQAAAAAAAAAAAEAAACHxsCatMvJ-rTL4rkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr1BGEK9QRhTG; BDUSS_BFESS=w5MTNla0VmTkJCdlRxMnM3bEVEelpjc2ZRZkZ-TzBhTklPWWZnVXd5Y0tnaXhoRVFBQUFBJCQAAAAAAAAAAAEAAACHxsCatMvJ-rTL4rkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr1BGEK9QRhTG; BAIDUID=E8BAAE642C79E8BB01836262C5BD81A1:FG=1; BDORZ=B490B5EBF6F3CD402E515D22BCDA1598; MCITY=-%3A; bdindexid=kf0so0lfd9o59mohqs1h09vr90; indexpro=htve70jb0hrfvstceem3kt9mg2; BD_HOME=1; H_PS_PSSID=34653_34439_34655_34004_34599_34585_34092_34106_26350_34627_34419_34555; sug=3; sugstore=0; ORIGIN=0; bdime=0; BA_HECTOR=a1210ka00l81a105ud1gk3qhu0q





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "longxiaofei/spider-BaiduIndex"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [longxiaofei/spider-BaiduIndex] 无法获取百度指数 (#57)





   
确认一下这个账号是否可以正常访问百度指数网站?
  
可以正常登录访问百度指数网站。
  
如果不介意的话，可以将这个账号的cookie发送到我邮箱吗?  ***@***.***
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by longxiaofei** [comment]
> 出现同样的问题

我把你的回复删了哈，cookies信息太敏感了

**Comment by cishengciyin** [comment]
哈哈哈没事的


有什么办法可以解决吗
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "longxiaofei/spider-BaiduIndex"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 晚上9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [longxiaofei/spider-BaiduIndex] 无法获取百度指数 (#57)





  
出现同样的问题
  
我把你的回复删了哈，cookies信息太敏感了
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by longxiaofei** [comment]
停掉这些账号的现有抓取，一天后重新尝试抓取。

这些账号临时被BAN了。

**Comment by grandioserver** [comment]
把获取间隔调整为10-20s一次，可以稳定运行了。感谢大佬！
